title: 'Between.Data.Lines'
author: 'mikolaj.fido@gmail.com'
# description: 'en'
# lang: 'en'
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# assets_path: 'assets/'

sass: # Enables the conversion of css/agency.min.scss to  css/agency.min.css
  style: compressed # Minify css/agency.min.css

collections: # Enables additional data structures 
  projects: # Enables _projects

# Build settings
theme: jekyll-theme-startbootstrap-agency
