title: 'between.data.lines'
description:  |
    It aims to combine best-in-class data science portfolio, personal website and engaging blog.
    It is created by quantitative analyst for those who share the same passion, occupy similar positions,
    pursue interesting opportunities in financial and data-driven world.
url: http://betweendatalines.com/
author: 'mikolaj.fido@gmail.com'
lang: 'en'
social:
  name: Mikolaj fido
  links:
    - https://github.com/mikolajf
    - https://www.linkedin.com/in/mikolaj-fido/
    - mailto:mikolaj.fido@gmail.com
logo: /assets/img/logo/logo.svg"
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# assets_path: 'assets/'

sass: # Enables the conversion of css/agency.min.scss to  css/agency.min.css
  style: compressed # Minify css/agency.min.css

collections: # Enables additional data structures
  projects: # Enables _projects

# Build settings
remote_theme: SotiriosVrachas/jekyll-theme-startbootstrap-agency@0.2.4
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
