brand:
  name: Between.data.lines
menu-string: Menu

nav:
  - title: About
    url: '#about'
  # - title: Services
  #   url: '#services'
  # - title: Portfolio
  # url: '#portfolio'
  - title: Storyline
    url: '#storyline'
  # - title: Contact
  #  url: '#contact'

copyright: Copyright &copy; Between.data.lines 2019

social-buttons:
  - icon: fa fa-github
    url: 'https://github.com/mikolajf' 
  - icon: fa fa-linkedin
    url: 'https://www.linkedin.com/in/mikolaj-fido/'
  - icon: fa fa-envelope
    url: 'mailto:mikolaj.fido@gmail.com'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
